services:
  server:
    image: ubuntu:latest
    volumes:
      - ./:/go/src/resweave
    working_dir: /go/src/resweave
    command: ["./bin/server"]
    #command: ["ls", "-F", "./bin/server"]
    ports:
      - 8080:8080
    networks:
      - backend

  libtest:
    image: ubuntu:latest
    volumes:
      - ./:/go/src/resweave
    working_dir: /go/src/resweave
    command: ["./bin/test" ]
    #command: ["ls", "-F","./bin/test" ]
    environment:
      - HOST_NAME=server
    networks:
      - backend
networks:
  backend: {}
