include::resweave.vars[]
:sonar-project-id: mortedecai_resweave
:img-quality-gate: https://sonarcloud.io/api/project_badges/measure?project={sonar-project-id}&metric=alert_status
:img-coverage: https://sonarcloud.io/api/project_badges/measure?project={sonar-project-id}&metric=coverage
:img-maintainability: https://sonarcloud.io/api/project_badges/measure?project={sonar-project-id}&metric=sqale_rating
:img-security-rating: https://sonarcloud.io/api/project_badges/measure?project={sonar-project-id}&metric=security_rating
:img-reliability: https://sonarcloud.io/api/project_badges/measure?project={sonar-project-id}&metric=reliability_rating
:img-techdebt: https://sonarcloud.io/api/project_badges/measure?project={sonar-project-id}&metric=sqale_index
:uri-analysis: https://sonarcloud.io/summary/new_code?id={sonar-project-id}
:toc:
:toc-placement!:
:icons: font
= Resweave

.Version: {resweave-version}

> Let developers worry about coding, not routing.

NOTE: This is an initial release with documentation and features expected to improve over time.

toc::[]

== Resource Based Web Server

Resweave is an opinionated, resource based web server intended to facilitate web application development.

In practice, this means that:

. Resource chains are used to specify pathing.
** Custom pathing is only allowed for a limited prefix.
. Resources have pre-defined possible functionality:
.. LIST - An HTTP `GET` to the `/<resource name>/` endpoint which returns a list `<resource>` entities.
.. CREATE - An HTTP `POST` to the `/<resource name>/` endpoint which attempts to create a new `<resource>` entity.
.. FETCH - An HTTP `GET` to the `/<resource name>/<id>` endpoint which attempts to retrieve the `<resource>` identified by `<id>`.
.. UPDATE - An HTTP `PATCH` or PUT to the `/<resource name>/<id>` endpoint which attempts to update the `<resource>` identified by `<id>`.
.. DELETE - An HTTP `DELETE` to the `/<resource name>/<id>` endpoint which attempts to delete the `<resource>` identified by `<id>`.
. Any combination of these behaviours (or none of them) can exist on a resource.
. Intelligent defaults
. Paths dynamically built from resources to avoid developers thinking about route ordering.

== Benefits of Resweave

* Resweaves encourages developers to think of their web applications in terms of resources.
* Simple, consistent coding paradigm makes consistency and maintenance easier.

== Commitment to Quality

Resweave makes use of SonarCloud to measure and track project quality.

|===
|image:{img-quality-gate}[Quality Gate,link={uri-analysis}]|image:{img-coverage}[Coverage,link={uri-analysis}] |image:{img-maintainability}[Maintainability,link={uri-analysis}] |image:{img-reliability}[Reliability,link={uri-analysis}] |image:{img-security-rating}[Security Rating,link={uri-analysis}] |image:{img-techdebt}[Technical Debt,link={uri-analysis}]
|===

== Additional Documentation

NOTE: The following documentation will be updated to link to it as it is created.

1. link:usage.html[Usage Documentation]
2. Quick Start Documentation
    a. Quick Start - HTML Server
    b. Quick Start - API Server
    c. Quick Start - TODO App
