name: Resweave CI/CD Build
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  code-check:
    name: Build and check code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.22'
      - run: ./project coverage
      - name: Static Check
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          # TODO(keithpaterson): figure out why we must use "latest" version to avoid an error here
          version: "2024.1"
          install-go: false
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          # we let the report trigger content trigger a failure using the GitHub Security features.
          args: './...'
      - name: Run Integration Tests
        if: ${{ contains(fromJson('["pull_request"]'), github.event_name) }}
        run: ./project test integration
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=mortedecai_resweave
            -Dsonar.organization=mortedecai
            -Dsonar.projectVersion=0.1.0-alpha
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.sources=.
            -Dsonar.exclusions=**/*_test.go,**/vendor/**,**/testing/integration/**/*.go
            -Dsonar.tests=.
            -Dsonar.test.exclusions=**/vendor/**
            -Dsonar.test.inclusions=**/*_test.go
            -Dsonar.go.coverage.reportPaths=.reports/coverage.out
            -Dsonar.go.tests.reportPaths=.reports/test.json

      - name: Archive Code Reports
        uses: actions/upload-artifact@v3
        with:
          name: project-reports
          path: .reports/

